dist: xenial
language: python
python: 3.7
after_success:
- coveralls
before_script:
- flake8 ntpdatetime -v
deploy:
  provider: pypi
  user: Iwan.in.t.Groen
  password:
    secure: Xsk3595uNcjB2s9j22+ibYEcdq8WPnsYIlY42hzNjIx6JQY8RA/zP7PIrJ0JLIiFXn5eDGEUxhLgCw2kKU6lbuLy/SFypueiEgHelFYf4Yi+V4kjYG0fY+0twK/8Ci6GImL8IvMskAmxxnc8VNggJERyjGn1IKqXyBCXmWPWx/3vMMuJ4la0wRxxqKaz3grmzH3wS4JofFYAgqDx+uFCu6KDBtU/BdZdPt+wh5KUj4UEqbmNt416t2TGKjc9DfvX3pid7BOwZgdMu4I3zuwsz9CN8yJKsMdWmKcpIzcevAdreesP6L5ROtaebYHxYG/dULiuoSzxvtrZ48VJJRiBem2N3gKAioZlorKtytY0AgggHNwYvbS5Gdv53kHoAQZFlIrvRsIuC7EkSI+9p9m1hNYaDqD4mTi5pCptnysf/KZYwpzcDGMHtUducEEMmbcbSI/ZSQtGT5F0bqaTAiHpRcr2IkpgEL+GWXsktReErNqod7xd1XfB4vWNcqj626jDSVRwfxHTxZ96hePyiykZHnPh+sbjG+IUcfJGoYpi46+K32EgblCR20C83zFhEysLpldfZJq0Ky99REDfu37sFWK7e837C3wyOIGY5IS6igGgaiAG289tc9TRlOiU3e1T6NISOMdwP7uSMpxBHDHExcgCXvDS0amB/CcDYk92bic=
  on:
    repo: igroen/ntpdatetime
    tags: true
  distributions: sdist bdist_wheel
env:
- TOXENV=py37
install:
- pip install -U tox
- pip install -U coveralls
- pip install -U flake8
script:
- tox
- coverage run --source=ntpdatetime setup.py test
